name: tonatona-logger
version: "0.2.0.2"
category: "System, Library, Tonatona"
synopsis: tonatona plugin for logging.
description:
  Tonatona plugin for logging.
  This package provides a tonatona plugin for logging.
license: "MIT"
author: "Kadzuya Okamoto, Dennis Gosnell"
copyright: "2018 Kadzuya Okamoto"
maintainer: "arow.okamoto+github@gmail.com"

tested-with: GHC==8.8.3, GHC==8.8.2, GHC==8.6.5, GHC==8.6.3, GHC==8.4.3, GHC==8.2.2

extra-source-files:
  - README.md

ghc-options: -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wredundant-constraints
default-extensions:
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 4.15
  - rio >= 0.1 && < 0.2
  - tonatona >= 0.1 && < 0.2
  - tonaparser >= 0.1 && < 0.2

library:
  source-dirs:
    - src
  exposed-modules:
    - Tonatona.Logger

tests:
  spec:
    main: "Spec.hs"
    other-modules: []
    source-dirs:
      - test
    dependencies:
      - tonatona
  doctest:
    main: "DocTest.hs"
    other-modules: []
    source-dirs:
      - test
    dependencies:
      - doctest
      - Glob

github: tonatona-project/tonatona
