on: [push, pull_request]

jobs:
  stack:
    name: stack - ${{ matrix.os }} - ghc ${{ matrix.plan.resolver }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        plan:
          - ghc: 8.8.3
            resolver: lts-16
          - ghc: 8.8.2
            resolver: lts-15
          - ghc: 8.6.5
            resolver: lts-14
          - ghc: 8.6.3
            resolver: lts-13
          - ghc: 8.4.3
            resolver: lts-12
          - ghc: 8.2.2
            resolver: lts-11
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 'latest'

      - uses: actions/cache@v2
        if: ${{ runner.os != 'macOS' }}
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ matrix.os }}-stack-${{ matrix.plan.resolver }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ matrix.os }}-stack-

      - name: test
        run: stack --no-terminal --system-ghc --resolver ${{ matrix.plan.resolver }} test --bench --no-run-benchmarks --haddock --no-haddock-deps --flag tonaparser:buildexample
